Лабораторные 1.1, 1.2, 1.3
danilproger/clojure_labs pull request #1
Opened 2022-10-02 16:56 UTC by danilproger

2022-10-03 19:49 UTC, shishkin-pavel requested changes
в первой и второй частях есть немного замечаний

2022-10-03 19:49 UTC, shishkin-pavel commented on src/clojure_labs/lab_1/lab_1_1.clj
> +  (if (<= n 1)
но для `n = 0` это даёт неправильный результат
кроме того, я бы хотел, чтобы ты вовсе избавился от функции `elems-to-list`, ведь есть единственный тривиальный результат для `n = 0`

2022-10-03 19:49 UTC, shishkin-pavel commented on src/clojure_labs/lab_1/lab_1_1.clj
> +(defn can-be-added?
мб код станет прозрачнее, если убрать эту функцию и предикат из неё поставить на место вызова

2022-10-03 19:49 UTC, shishkin-pavel commented on src/clojure_labs/lab_1/lab_1_2.clj
> +  ([perm elems] (add-elem-to-perm perm elems (list)))
вместо нескольких перегрузок (теперь все они публичные!) предлагается использовать `loop`
вопрос на подумать после того, как переделаешь на лупы: как рекур определяет куда надо прыгнуть? исходя из этого, можем ли мы изобрести луп "на коленке" из базовых кложуровских средств?

2022-10-03 19:49 UTC, shishkin-pavel commented on src/clojure_labs/lab_1/lab_1_3.clj
> +(defn my-map-no-reduce
было бы логично просто написать свой редьюс вместо таких мапов и фильтров =) но допустим ок

2022-10-04 02:36 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_3.clj
> +(defn my-map-no-reduce
в целом да, просто в задании лабы было написано слепить свой map и filter через reduce, но на паре говорили без них писать, поэтому решил как-то так несколько вариантов накидать

2022-10-04 02:37 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_2.clj
> +  ([perm elems] (add-elem-to-perm perm elems (list)))
а по количеству аргументов рекур не может понять куда прыгнуть? (2 или 3 соответственно)

2022-10-04 08:07 UTC, shishkin-pavel commented on src/clojure_labs/lab_1/lab_1_2.clj
> +  ([perm elems] (add-elem-to-perm perm elems (list)))
а если количество аргументов у функций в текущем лексическом контексте одинаковое, то как понять? =)
надо поискать что-то типа recursion point

2022-10-08 11:43 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_2.clj
> +  ([perm elems] (add-elem-to-perm perm elems (list)))
recur прыгает на ближайший loop или функцию

2022-10-08 12:36 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_1.clj
> +  (if (<= n 1)
elems-to-list убрал, теперь проверка на <= 0

2022-10-08 12:37 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_1.clj
> +(defn can-be-added?
думал так понятнее, но ок, убрал предикат

2022-10-08 12:37 UTC, danilproger commented on src/clojure_labs/lab_1/lab_1_2.clj
> +  ([perm elems] (add-elem-to-perm perm elems (list)))
перевел на loop

2022-10-23 21:29 UTC, shishkin-pavel approved these changes

2022-10-24 14:53 UTC, merged