Лабораторная 2.1
danilproger/clojure_labs pull request #2
Opened 2022-11-06 16:24 UTC by danilproger

2022-11-21 13:20 UTC, shishkin-pavel requested changes
интегралы должны считаються неправильно (смотри комментарии)

2022-11-21 13:20 UTC, shishkin-pavel commented on src/clojure_labs/lab_2/lab_2_1.clj
> +(def memoized-integrate-integer
https://t.me/c/1568036009/155
тут надо немножко починить и будет норм

2022-11-21 13:20 UTC, shishkin-pavel commented on src/clojure_labs/lab_2/lab_2_1.clj
> +       (recur (dec x) (+ acc (count-integrate f (dec x) x delta)))))))
для следующего шага нужно не просто декрементировать единицу, а вычитать дельту
кроме того, что будет, если дельта не кратна общему отрезку? (например, интеграл от нуля до десяти с шагом 3)

2022-11-21 13:20 UTC, shishkin-pavel commented on src/clojure_labs/lab_2/lab_2_1.clj
> +  (+ (count-integrate f (int x) x delta)
кажется, это попытка таки выровнять на шаг, но не учитывается, что шаг может быть не равен единице
также не понимаю, почему бы просто не прибавить одну трапецию вместо одного из слагаемых (ведь обе функции считают сумму частичных??)

2022-11-21 13:20 UTC, shishkin-pavel commented on src/clojure_labs/lab_2/lab_2_1.clj
> +  (+ (count-integrate f (int x) x delta)
то же самое, что и в похожей функции выше

2022-11-21 13:20 UTC, shishkin-pavel commented on src/clojure_labs/lab_2/lab_2_1.clj
> +(def dx 0.0001)
`let` куда как красивше

2022-11-27 14:19 UTC, danilproger commented on src/clojure_labs/lab_2/lab_2_1.clj
> +(def memoized-integrate-integer
memoize вынесено в let, чтоб глобально не кешировалось

2022-11-27 14:19 UTC, danilproger commented on src/clojure_labs/lab_2/lab_2_1.clj
> +       (recur (dec x) (+ acc (count-integrate f (dec x) x delta)))))))
теперь вычитается дельта, отрезок приводится к кратному по отрезку

2022-11-27 14:19 UTC, danilproger commented on src/clojure_labs/lab_2/lab_2_1.clj
> +  (+ (count-integrate f (int x) x delta)
вообще выкосил эту функцию

2022-11-27 14:19 UTC, danilproger commented on src/clojure_labs/lab_2/lab_2_1.clj
> +  (+ (count-integrate f (int x) x delta)
и эту тоже выкосил

2022-11-27 14:19 UTC, danilproger commented on src/clojure_labs/lab_2/lab_2_1.clj
> +(def dx 0.0001)
переписано на let

2022-12-04 11:58 UTC, shishkin-pavel approved these changes
выглядит похоже на правду

2022-12-04 12:21 UTC, merged